/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medida.presentacion.view;

import applicationpresentacion.Application;
import java.util.Observable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import medida.presentacion.controller.MedidasController;
import medida.presentacion.model.MedidasModel;
import tipoinstrumentos.presentacion.controller.TipoInstrumentosController;
import tipoinstrumentos.presentacion.model.TipoInstrumentosModel;
import tipoinstrumentos.presentacion.view.TipoInstrumentoView;

/**
 *
 * @author pc
 */
public class MedidasView extends javax.swing.JInternalFrame implements java.util.Observer {
    
    MedidasController control;
    MedidasModel model;

       public MedidasController getControl() {
        return control;
    }

    public void setControl(MedidasController control) {
        this.control = control;
    }

    public MedidasModel getModel() {
        return model;
    }

    public void setModel(MedidasModel model) {
        this.model = model;
        
        model.addObserver(this);
    }
    
    
    
    
    /**
     * Creates new form MedidasView
     */
    public MedidasView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregarEstados = new javax.swing.JButton();
        btnEliminarInstrumento = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        medidasTable = new javax.swing.JTable();
        descripcionLabel = new javax.swing.JLabel();
        descripcionField = new javax.swing.JTextField();
        btnBuscarInstrumento = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Medidas");
        setVisible(true);

        btnAgregarEstados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/view/icons/add.png"))); // NOI18N
        btnAgregarEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEstadosActionPerformed(evt);
            }
        });

        btnEliminarInstrumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/view/icons/delete.png"))); // NOI18N
        btnEliminarInstrumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarInstrumentoActionPerformed(evt);
            }
        });

        medidasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        medidasTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medidasTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(medidasTable);

        descripcionLabel.setText("Descripcion");

        btnBuscarInstrumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/view/icons/search.png"))); // NOI18N
        btnBuscarInstrumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarInstrumentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(descripcionLabel)
                        .addGap(26, 26, 26)
                        .addComponent(descripcionField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnBuscarInstrumento, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarInstrumento, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descripcionLabel)
                    .addComponent(descripcionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarInstrumento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(btnEliminarInstrumento)
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEstadosActionPerformed

        Application.MEDIDA_VIEW.setLocation(this.btnAgregarEstados.getLocationOnScreen());
        int row = this.medidasTable.getSelectedRow();

        control.preAgregar();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarEstadosActionPerformed

    private void btnEliminarInstrumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarInstrumentoActionPerformed

        int row = this.medidasTable.getSelectedRow();

        if(row != -1){

            if(JOptionPane.showConfirmDialog(null , "Esta seguro", "Borrar Instrumento" ,  JOptionPane.YES_NO_OPTION ) == JOptionPane.YES_OPTION){

                try {
                    control.borrar(row);
                } catch (Exception ex) {
                    Logger.getLogger(MedidaView.class.getName()).log(Level.SEVERE, null, ex);
                }
                control.buscar();
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarInstrumentoActionPerformed

    private void medidasTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medidasTableMouseClicked

        if (evt.getClickCount() == 2) {
            int row = this.medidasTable.getSelectedRow();
            Application.MEDIDA_VIEW.setLocation(evt.getLocationOnScreen());

            this.medidasTable.setAutoCreateRowSorter(true);
            control.editar(row);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_medidasTableMouseClicked

    private void btnBuscarInstrumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarInstrumentoActionPerformed

        control.buscar();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarInstrumentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedidasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedidasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedidasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedidasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedidasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEstados;
    private javax.swing.JButton btnBuscarInstrumento;
    private javax.swing.JButton btnEliminarInstrumento;
    public javax.swing.JTextField descripcionField;
    private javax.swing.JLabel descripcionLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable medidasTable;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {
        
          if(model.getErrores().get("descripcionField")!= null){
        
          
            descripcionLabel.setToolTipText(model.getErrores().get("descripcionField"));
        
        
        } else {
        
            descripcionLabel.setBorder(null);
            descripcionLabel.setToolTipText("");
        
        
        }
        
        medidasTable.setModel(model.getMedidas());
        this.revalidate();
        if(!model.getMensaje().equals("")){
        
            JOptionPane.showMessageDialog(this, model.getMensaje(), "", JOptionPane.INFORMATION_MESSAGE);
        
        }
        
        
        
        
    }
}
