/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tipoinstrumentos.presentacion.view;

import instrumento.entidades.TipoInstrumento;
import javax.swing.JOptionPane;
import applicationpresentacion.Application;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
 
import tipoinstrumentos.presentacion.controller.TipoInstrumentoController;
import tipoinstrumentos.presentacion.controller.TipoInstrumentosController;
import tipoinstrumentos.presentacion.model.TipoInstrumentoModel;
 
/**
 *
 * @author jsanchez
 */
public class TipoInstrumentoView extends javax.swing.JDialog implements java.util.Observer {

    /**
     * Creates new form PersonaView
     */
    public TipoInstrumentoView(java.awt.Frame parent, boolean modal) {
        super(parent,modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexoFld = new javax.swing.ButtonGroup();
        idLbl = new javax.swing.JLabel();
        nombreLbl = new javax.swing.JLabel();
        sexoLbl = new javax.swing.JLabel();
        guardarFld = new javax.swing.JButton();
        cancelarFld = new javax.swing.JButton();
        codigoFld = new javax.swing.JTextField();
        nombreFld = new javax.swing.JTextField();
        unidadField = new javax.swing.JTextField();

        setTitle("Tipo Instrumento");

        idLbl.setText("Codigo");

        nombreLbl.setText("Nombre");

        sexoLbl.setText("Unidad");

        guardarFld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/view/icons/save.png"))); // NOI18N
        guardarFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarFldActionPerformed(evt);
            }
        });

        cancelarFld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/view/icons/cancel.png"))); // NOI18N
        cancelarFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarFldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sexoLbl)
                    .addComponent(nombreLbl)
                    .addComponent(idLbl))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(guardarFld, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(cancelarFld, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreFld, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(unidadField, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(codigoFld))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLbl)
                    .addComponent(codigoFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLbl)
                    .addComponent(nombreFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexoLbl)
                    .addComponent(unidadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelarFld, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardarFld))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarFldActionPerformed
        try {
            this.controller.guardar();
             
            
            if(model.getModo() == Application.MODO_EDITAR){
            JOptionPane.showMessageDialog(this, "Tipo Instrumento Editado");
            }
            
            if(model.getModo() == Application.MODO_AGREGAR){
            JOptionPane.showMessageDialog(this, "Tipo Instrumento Agregado");
            }
            
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(TipoInstrumentoView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(TipoInstrumentoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
        
    }//GEN-LAST:event_guardarFldActionPerformed

    private void cancelarFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarFldActionPerformed
      
        
        this.setVisible(false);
    }//GEN-LAST:event_cancelarFldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoInstrumentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoInstrumentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoInstrumentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoInstrumentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cancelarFld;
    public javax.swing.JTextField codigoFld;
    public javax.swing.JButton guardarFld;
    public javax.swing.JLabel idLbl;
    public javax.swing.JTextField nombreFld;
    public javax.swing.JLabel nombreLbl;
    private javax.swing.ButtonGroup sexoFld;
    public javax.swing.JLabel sexoLbl;
    public javax.swing.JTextField unidadField;
    // End of variables declaration//GEN-END:variables
    
    TipoInstrumentoController controller;
    TipoInstrumentosController inscontrol;
   
     
    TipoInstrumentoModel model;
   

    public TipoInstrumentoController getController() {
        return controller;
    }

    public void setController(TipoInstrumentoController controller) {
        this.controller = controller;
    }

    public TipoInstrumentoModel getModel() {
        return model;
    }

    public void setModel(TipoInstrumentoModel model) {
        this.model = model;
        model.addObserver(this);
    }
    
     
    
    
    @Override
   public void update(java.util.Observable updatedModel,Object parametros){
       TipoInstrumento instrumentoCurrent = model.getCurrent();
        
       
       
      
       
         nombreFld.setText(instrumentoCurrent.getNombre());
       if (model.getErrores().get("Nombre")!=null){
            
            idLbl.setToolTipText(model.getErrores().get("Nombre"));
        }
        else{
            idLbl.setBorder(null);
            idLbl.setToolTipText("");
        }
       
         unidadField.setText(instrumentoCurrent.getUnidad());
       if (model.getErrores().get("Unidad")!=null){
            
            idLbl.setToolTipText(model.getErrores().get("Unidad"));
        }
        else{
            idLbl.setBorder(null);
            idLbl.setToolTipText("");
        }
 
}


}


