/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instrumento.presentacion.view;

import applicationpresentacion.Application;
import calibracion.presentacion.controller.CalibracionesController;
import calibracion.presentacion.model.CalibracionesModel;
import calibracion.presentacion.view.CalibracionesView;
import instrumento.entidades.Instrumento;
import instrumento.presentacion.controller.InstrumentosController;
import instrumento.presentacion.model.InstrumentoTableModel;
import instrumento.presentacion.model.InstrumentosModel;
import java.sql.SQLException;
import java.util.Observable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import medida.presentacion.controller.MedidasController;

/**
 *
 * @author pc
 */
public class InstrumentosView extends javax.swing.JInternalFrame implements java.util.Observer{
    
    InstrumentosController control;
    InstrumentosModel model;
    MedidasController mcontrol;
    
    
 
    CalibracionesController calibracionescon;
    
    public void setController(InstrumentosController controller){
        this.control=controller;
    }
    public void setModel(InstrumentosModel model){
        this.model=model;
         model.addObserver(this);
    }

    public InstrumentosModel getModel() {
        return model;
    }
    

    /**
     * Creates new form InstrumentosView
     */
    public InstrumentosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminarInstrumento = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        InstrumentoTable = new javax.swing.JTable();
        descripcionLabel = new javax.swing.JLabel();
        descripcionField = new javax.swing.JTextField();
        btnBuscarInstrumento = new javax.swing.JButton();
        btnAgregarEstados = new javax.swing.JButton();
        calibracionesBoton = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Instrumentos");
        setVisible(true);

        btnEliminarInstrumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/view/icons/delete.png"))); // NOI18N
        btnEliminarInstrumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarInstrumentoActionPerformed(evt);
            }
        });

        InstrumentoTable.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        InstrumentoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        InstrumentoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InstrumentoTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InstrumentoTableMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                InstrumentoTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(InstrumentoTable);

        descripcionLabel.setText("Descripcion");

        btnBuscarInstrumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/view/icons/search.png"))); // NOI18N
        btnBuscarInstrumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarInstrumentoActionPerformed(evt);
            }
        });

        btnAgregarEstados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/view/icons/add.png"))); // NOI18N
        btnAgregarEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEstadosActionPerformed(evt);
            }
        });

        calibracionesBoton.setText("()");
        calibracionesBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calibracionesBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(descripcionLabel)
                        .addGap(26, 26, 26)
                        .addComponent(descripcionField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnBuscarInstrumento, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminarInstrumento, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calibracionesBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descripcionLabel)
                    .addComponent(descripcionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarInstrumento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(calibracionesBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarInstrumento)
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarInstrumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarInstrumentoActionPerformed

        int row = this.InstrumentoTable.getSelectedRow();

        if(row != -1){

            if(JOptionPane.showConfirmDialog(null , "Esta seguro", "Borrar Instrumento" ,  JOptionPane.YES_NO_OPTION ) == JOptionPane.YES_OPTION){

                try {
                    control.borrar(row);
                } catch (Exception ex) {
                    Logger.getLogger(InstrumentoView.class.getName()).log(Level.SEVERE, null, ex);
                }
                control.buscar();
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarInstrumentoActionPerformed

    private void InstrumentoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstrumentoTableMouseClicked

         
       
        
        if (evt.getClickCount() == 2) {
            int row = this.InstrumentoTable.getSelectedRow();
            Application.INSTRUMENTO_VIEW.setLocation(evt.getLocationOnScreen());
             
            Application.INSTRUMENTO_VIEW.serieFld.setEditable(false);

            this.InstrumentoTable.setAutoCreateRowSorter(true);
           
            control.editar1(row);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_InstrumentoTableMouseClicked

    private void btnBuscarInstrumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarInstrumentoActionPerformed

        control.buscar();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarInstrumentoActionPerformed

    private void btnAgregarEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEstadosActionPerformed

        Application.TIPOINSTRUMENTO_VIEW.setLocation(this.btnAgregarEstados.getLocationOnScreen());
     
        
        int row = this.InstrumentoTable.getSelectedRow();

         
        control.preAgregar();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarEstadosActionPerformed

    private void calibracionesBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calibracionesBotonActionPerformed

     
          
         
     //   medicionesTextField.setText(Integer.toString(seleccionada.getMedida()));
       
         
        
        System.out.println("clicks " + clicks);
        
        if(clicks == 1){
         clicks = 0;
         
          int row = this.InstrumentoTable.getSelectedRow();
             
             
            

            this.InstrumentoTable.setAutoCreateRowSorter(true);
            control.editar(row);
             
            
         
         
         
         //InstrumentoTableModel mod =  (InstrumentoTableModel) InstrumentoTable.getModel();
         //int row = this.InstrumentoTable.getSelectedRow();
        // String a = mod.getValueAt(row, 2).toString();
         
        // Instrumento seleccionada = model.getInstrumentos().getRowAt(row); 
         
        // System.out.println("aa " + a);
        // calibracionesview.descripcionField.setText(a);
      //  calibracionesview.setAux(a);
      //  calibracionesview.setVisible(true);
        
        // System.out.println("aa despues " + calibracionesview.getAux());
        
         // CalibracionesView cv = new CalibracionesView(a);
         // cv.descripcionField.setText(a);
         // cv.setVisible(true);
        
         
        // System.out.println("a " + a);
          //Application.CALIBRACIONES_VIEW.setLocation(this.calibracionesBoton.getLocationOnScreen());
        
       // Application.PRUEBACAL_VIEW.setLocation(this.calibracionesBoton.getLocationOnScreen());
       // Application.PRUEBACAL_VIEW.setVisible(true);
        
         // Application.CALIBRACIONES_VIEW.setVisible(true);
        
        
          

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_calibracionesBotonActionPerformed

    private void InstrumentoTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstrumentoTableMousePressed

        clicks = 1;

// TODO add your handling code here:
    }//GEN-LAST:event_InstrumentoTableMousePressed

    private void InstrumentoTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstrumentoTableMouseEntered

        control.buscar();
        // TODO add your handling code here:
    }//GEN-LAST:event_InstrumentoTableMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstrumentosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstrumentosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstrumentosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstrumentosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstrumentosView().setVisible(true);
            }
        });
    }

    @Override
    public void update(Observable o, Object o1) {
        
        
        
        
          if(model.getErrores().get("descripcionField")!= null){
        
          
            descripcionLabel.setToolTipText(model.getErrores().get("descripcionField"));
        
        
        } else {
        
            descripcionLabel.setBorder(null);
            descripcionLabel.setToolTipText("");
        
        
        }
        
        InstrumentoTable.setModel(model.getInstrumentos());
        this.revalidate();
        if(!model.getMensaje().equals("")){
        
            JOptionPane.showMessageDialog(this, model.getMensaje(), "", JOptionPane.INFORMATION_MESSAGE);
        
        }
        
        
    }
    
    int clicks;

    String aux = "a";
    
    void setAux(String a){
    
        aux = a;
    
    }
    
    public String getAux(){
    
        return aux;
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable InstrumentoTable;
    private javax.swing.JButton btnAgregarEstados;
    private javax.swing.JButton btnBuscarInstrumento;
    private javax.swing.JButton btnEliminarInstrumento;
    private javax.swing.JButton calibracionesBoton;
    public javax.swing.JTextField descripcionField;
    private javax.swing.JLabel descripcionLabel;
    public javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
