/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instrumento.presentacion.view;

import applicationpresentacion.Application;
import instrumento.entidades.Instrumento;
 
import instrumento.presentacion.controller.InstrumentoController;
import instrumento.presentacion.model.InstrumentoModel;
 
import java.util.Observable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
 

/**
 *
 * @author pc
 */
public class InstrumentoView extends javax.swing.JDialog implements java.util.Observer {

    /**
     * Creates new form InstrumentoView
     */
    public InstrumentoView(java.awt.Frame parent, boolean modal) {
        super(parent,modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexoLbl = new javax.swing.JLabel();
        guardarFld = new javax.swing.JButton();
        cancelarFld = new javax.swing.JButton();
        serieFld = new javax.swing.JTextField();
        descripcionField = new javax.swing.JTextField();
        serieTF = new javax.swing.JLabel();
        nombreLbl = new javax.swing.JLabel();
        minimolb = new javax.swing.JLabel();
        sexoLbl2 = new javax.swing.JLabel();
        minimoField = new javax.swing.JTextField();
        maximoField = new javax.swing.JTextField();
        sexoLbl3 = new javax.swing.JLabel();
        ToleranciaField = new javax.swing.JTextField();
        tipoFld = new javax.swing.JComboBox();

        setTitle("Instrumento");

        sexoLbl.setText("Descripcion");

        guardarFld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/view/icons/save.png"))); // NOI18N
        guardarFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarFldActionPerformed(evt);
            }
        });

        cancelarFld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/view/icons/cancel.png"))); // NOI18N
        cancelarFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarFldActionPerformed(evt);
            }
        });

        serieTF.setText("Serie");

        nombreLbl.setText("Tipo");

        minimolb.setText("Minimo");

        sexoLbl2.setText("Maximo");

        sexoLbl3.setText("Tolerancia");

        tipoFld.setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sexoLbl3)
                    .addComponent(sexoLbl2)
                    .addComponent(minimolb)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sexoLbl)
                            .addComponent(nombreLbl)
                            .addComponent(serieTF))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(guardarFld, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(cancelarFld, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipoFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(descripcionField, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                        .addComponent(serieFld)
                                        .addComponent(minimoField, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                        .addComponent(maximoField, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                        .addComponent(ToleranciaField, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)))))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serieTF)
                    .addComponent(serieFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLbl)
                    .addComponent(tipoFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexoLbl)
                    .addComponent(descripcionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minimolb)
                    .addComponent(minimoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexoLbl2)
                    .addComponent(maximoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexoLbl3)
                    .addComponent(ToleranciaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guardarFld, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cancelarFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarFldActionPerformed
        try {
            this.controller.guardar();
            
            if(model.getModo() == Application.MODO_EDITAR){
            JOptionPane.showMessageDialog(this, "Instrumento Editado");
            }
            
            if(model.getModo() == Application.MODO_AGREGAR){
            JOptionPane.showMessageDialog(this, "Instrumento Agregado");
            }
            
            
            
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al agregar Instrumento");
        }
    }//GEN-LAST:event_guardarFldActionPerformed

    private void cancelarFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarFldActionPerformed

        this.setVisible(false);
    }//GEN-LAST:event_cancelarFldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstrumentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstrumentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstrumentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstrumentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 
            }
        });
    }
    
    InstrumentoController controller;
    InstrumentoModel model;
    
    
    public void setController(instrumento.presentacion.controller.InstrumentoController controller){
        this.controller=controller;
    }
    public void setModel(instrumento.presentacion.model.InstrumentoModel model){
        this.model=model;
         model.addObserver(this);
    }

    public InstrumentoModel getModel() {
        return model;
    }

    @Override
    public void update(Observable o, Object o1) {
        
         
          Instrumento instrumentoCurrent = model.getCurrent();
          
          
        
         serieFld.setText(instrumentoCurrent.getSerie());
       if (model.getErrores().get("Serie")!=null){
            
            serieFld.setToolTipText(model.getErrores().get("Serie"));
        }
        else{
            serieFld.setBorder(null);
            serieFld.setToolTipText("");
        }
       
        
       
         descripcionField.setText(instrumentoCurrent.getDescripcion());
       if (model.getErrores().get("Descripcion")!=null){
            
            descripcionField.setToolTipText(model.getErrores().get("Descripcion"));
        }
        else{
            descripcionField.setBorder(null);
            descripcionField.setToolTipText("");
        }
       
         minimoField.setText(Integer.toString(instrumentoCurrent.getMinimo()));
       if (model.getErrores().get("Minimo")!=null){
            
            minimoField.setToolTipText(model.getErrores().get("Minimo"));
        }
        else{
            minimoField.setBorder(null);
            minimoField.setToolTipText("");
        }
       
        maximoField.setText(Integer.toString(instrumentoCurrent.getMaximo()));
       if (model.getErrores().get("Maximo")!=null){
            
            maximoField.setToolTipText(model.getErrores().get("Maximo"));
        }
        else{
            maximoField.setBorder(null);
            maximoField.setToolTipText("");
        }
       
       ToleranciaField.setText(Integer.toString(instrumentoCurrent.getTolerancia()));
       if (model.getErrores().get("Tolerancia")!=null){
            
            ToleranciaField.setToolTipText(model.getErrores().get("Tolerancia"));
        }
        else{
            ToleranciaField.setBorder(null);
            ToleranciaField.setToolTipText("");
        }
 
 
       tipoFld.removeAllItems();
        controller.iniciarCombo();
        
        
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField ToleranciaField;
    public javax.swing.JButton cancelarFld;
    public javax.swing.JTextField descripcionField;
    public javax.swing.JButton guardarFld;
    public javax.swing.JTextField maximoField;
    public javax.swing.JTextField minimoField;
    public javax.swing.JLabel minimolb;
    public javax.swing.JLabel nombreLbl;
    public javax.swing.JTextField serieFld;
    public javax.swing.JLabel serieTF;
    public javax.swing.JLabel sexoLbl;
    public javax.swing.JLabel sexoLbl2;
    public javax.swing.JLabel sexoLbl3;
    public javax.swing.JComboBox tipoFld;
    // End of variables declaration//GEN-END:variables
}
